<a href="https://colab.research.google.com/github/NBK-code/PyTorch_Basics/blob/main/PyTorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

##Back propagation for scalar output

In [2]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.9640,  0.6693, -0.1730], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([2.9640, 2.6693, 1.8270], grad_fn=<AddBackward0>)


In [4]:
z = y*y*2
print(z)

tensor([17.5707, 14.2498,  6.6755], grad_fn=<MulBackward0>)


In [5]:
z = z.mean()
print(z)

tensor(12.8320, grad_fn=<MeanBackward0>)


In [6]:
print(x.grad)

None


In [7]:
z.backward() #Calculates dz/dx
# z is a scalar value
print(x.grad)

tensor([3.9520, 3.5590, 2.4359])


##Back propagation for vector output

In [8]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.8006,  0.5123,  1.0057], requires_grad=True)


In [9]:
y = x + 2
print(y)

tensor([1.1994, 2.5123, 3.0057], grad_fn=<AddBackward0>)


In [10]:
z = y*y*2
print(z)

tensor([ 2.8769, 12.6237, 18.0690], grad_fn=<MulBackward0>)


In [11]:
v = torch.tensor([0.1, 1.0, 0.001], dtype = torch.float32)
print(v)

tensor([0.1000, 1.0000, 0.0010])


In [12]:
z.backward(v)
print(x.grad)

tensor([ 0.4797, 10.0493,  0.0120])


##Preventing tracking of gradients

In [13]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.1068, -0.1061,  0.0385], requires_grad=True)


In [14]:
#Option 1
# x.requires_grad_(False)

#Option 2
# x.detach()

#Option 3
# with torch.no_grad():

In [15]:
x.requires_grad_(False)

tensor([ 0.1068, -0.1061,  0.0385])

In [16]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.1635,  1.4000, -1.7137], requires_grad=True)


In [17]:
y = x.detach()
print(y)

tensor([ 0.1635,  1.4000, -1.7137])


In [18]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.1959,  0.2362,  0.0160], requires_grad=True)


In [19]:
with torch.no_grad():
  y = x+2
  print(y)

tensor([1.8041, 2.2362, 2.0160])


In [20]:
y = x+2
print(y)

tensor([1.8041, 2.2362, 2.0160], grad_fn=<AddBackward0>)


In [21]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights * 3).sum()
  model_output.backward()
  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


Gradients get accumulated in the grad attribute. To avoid this, set them to zero everytime.

In [22]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights * 3).sum()
  model_output.backward()
  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
