<a href="https://colab.research.google.com/github/NBK-code/PyTorch_Basics/blob/main/PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

1.12.1+cu113


##Tensors

In [3]:
x = torch.empty(1)
print(x)

tensor([9.2662e-36])


In [4]:
x = torch.empty(3)
print(x)

tensor([9.2664e-36, 0.0000e+00, 5.0447e-44])


In [5]:
x = torch.empty(2, 3)
print(x)

tensor([[9.2666e-36, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


In [6]:
x = torch.empty(2, 3, 3)
print(x)

tensor([[[9.2751e-36, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [7]:
x = torch.rand(2)
print(x)

tensor([0.5785, 0.3554])


In [8]:
x = torch.rand(2,2)
print(x)

tensor([[0.7433, 0.9734],
        [0.9439, 0.3741]])


In [9]:
x = torch.ones(1,2)
print(x)

tensor([[1., 1.]])


In [10]:
x = torch.ones(1,2)
print(x)
print(x.dtype)

tensor([[1., 1.]])
torch.float32


In [11]:
x = torch.ones(1,2, dtype = torch.int)
print(x)
print(x.dtype)

tensor([[1, 1]], dtype=torch.int32)
torch.int32


In [12]:
x = torch.ones(1,2, dtype = torch.double)
print(x)
print(x.dtype)

tensor([[1., 1.]], dtype=torch.float64)
torch.float64


In [13]:
x = torch.ones(1,2, dtype = torch.float16)
print(x)
print(x.dtype)

tensor([[1., 1.]], dtype=torch.float16)
torch.float16


In [14]:
x = torch.ones(1,2)
print(x)
print(x.size())

tensor([[1., 1.]])
torch.Size([1, 2])


In [15]:
x = torch.tensor([1.6, 2.3])
print(x)

tensor([1.6000, 2.3000])


In [16]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = x + y
print(z)

tensor([[0.7068, 0.1873],
        [0.7350, 0.7223]])
tensor([[0.4731, 0.3956],
        [0.8422, 0.5021]])
tensor([[1.1799, 0.5829],
        [1.5772, 1.2244]])


In [17]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = torch.add(x, y)
print(z)

tensor([[0.0948, 0.3875],
        [0.2704, 0.2958]])
tensor([[0.8841, 0.8490],
        [0.2848, 0.0716]])
tensor([[0.9789, 1.2365],
        [0.5552, 0.3674]])


Every function ending with an underscore does inplace operations.

In [18]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.9726, 0.3250],
        [0.1191, 0.1127]])
tensor([[0.3678, 0.7299],
        [0.1748, 0.5132]])
tensor([[1.3404, 1.0549],
        [0.2939, 0.6259]])


In [19]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = x - y
print(z)

tensor([[0.2282, 0.3435],
        [0.0378, 0.2096]])
tensor([[0.3865, 0.4068],
        [0.3551, 0.5273]])
tensor([[-0.1583, -0.0632],
        [-0.3173, -0.3177]])


In [20]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = torch.sub(x, y)
print(z)

tensor([[0.9488, 0.8046],
        [0.6629, 0.6637]])
tensor([[0.0687, 0.6350],
        [0.6404, 0.6625]])
tensor([[0.8801, 0.1696],
        [0.0225, 0.0012]])


In [21]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.sub_(x)
print(y)

tensor([[0.1591, 0.1344],
        [0.6066, 0.3698]])
tensor([[0.4676, 0.5200],
        [0.4354, 0.5992]])
tensor([[ 0.3085,  0.3855],
        [-0.1712,  0.2294]])


In [22]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = x * y
print(z)

tensor([[0.8544, 0.0730],
        [0.1779, 0.8006]])
tensor([[0.1231, 0.0574],
        [0.2622, 0.0701]])
tensor([[0.1052, 0.0042],
        [0.0467, 0.0561]])


In [23]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = torch.mul(x, y)
print(z)

tensor([[0.4831, 0.9808],
        [0.2235, 0.4685]])
tensor([[0.5459, 0.5594],
        [0.1941, 0.8754]])
tensor([[0.2637, 0.5487],
        [0.0434, 0.4101]])


In [24]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.mul_(x)
print(y)

tensor([[0.2958, 0.8243],
        [0.0531, 0.3394]])
tensor([[0.3092, 0.9519],
        [0.2753, 0.1422]])
tensor([[0.0915, 0.7847],
        [0.0146, 0.0483]])


In [25]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = x / y
print(z)

tensor([[0.2024, 0.3769],
        [0.3729, 0.4620]])
tensor([[0.0434, 0.1765],
        [0.7181, 0.6648]])
tensor([[4.6612, 2.1352],
        [0.5193, 0.6949]])


In [26]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = torch.div(x, y)
print(z)

tensor([[0.1855, 0.3424],
        [0.4276, 0.3650]])
tensor([[0.3012, 0.2628],
        [0.8424, 0.8079]])
tensor([[0.6159, 1.3030],
        [0.5076, 0.4517]])


In [27]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
y.div_(x)
print(y)

tensor([[0.0456, 0.5876],
        [0.5983, 0.3406]])
tensor([[0.0140, 0.7111],
        [0.1220, 0.4575]])
tensor([[0.3064, 1.2102],
        [0.2039, 1.3431]])


In [30]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])

tensor([[0.1460, 0.7097, 0.7493],
        [0.7908, 0.9119, 0.7880],
        [0.0641, 0.9806, 0.3420],
        [0.8072, 0.0878, 0.4290],
        [0.0186, 0.8764, 0.0051]])
tensor([0.1460, 0.7908, 0.0641, 0.8072, 0.0186])


In [32]:
x = torch.rand(5, 3)
print(x[0,0])
print(x[0,0].item())

tensor(0.8855)
0.8854544758796692


In [35]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)

tensor([[0.2817, 0.7367, 0.5479, 0.4533],
        [0.9851, 0.5052, 0.9534, 0.4043],
        [0.1497, 0.0860, 0.5449, 0.7280],
        [0.5435, 0.2908, 0.7159, 0.7549]])
tensor([0.2817, 0.7367, 0.5479, 0.4533, 0.9851, 0.5052, 0.9534, 0.4043, 0.1497,
        0.0860, 0.5449, 0.7280, 0.5435, 0.2908, 0.7159, 0.7549])


In [36]:
x = torch.rand(4, 4)
print(x)
y = x.view(-1, 8)
print(y)

tensor([[0.5230, 0.4818, 0.9641, 0.1360],
        [0.7590, 0.8321, 0.9969, 0.7105],
        [0.7168, 0.8336, 0.6255, 0.8609],
        [0.0346, 0.0319, 0.1714, 0.9052]])
tensor([[0.5230, 0.4818, 0.9641, 0.1360, 0.7590, 0.8321, 0.9969, 0.7105],
        [0.7168, 0.8336, 0.6255, 0.8609, 0.0346, 0.0319, 0.1714, 0.9052]])


In [37]:
x = torch.rand(4, 4)
print(x)
y = x.view(-1, 2)
print(y)

tensor([[0.3690, 0.9625, 0.6110, 0.9163],
        [0.3352, 0.0044, 0.2447, 0.7138],
        [0.6236, 0.4695, 0.3570, 0.8801],
        [0.3034, 0.0538, 0.7691, 0.2300]])
tensor([[0.3690, 0.9625],
        [0.6110, 0.9163],
        [0.3352, 0.0044],
        [0.2447, 0.7138],
        [0.6236, 0.4695],
        [0.3570, 0.8801],
        [0.3034, 0.0538],
        [0.7691, 0.2300]])


In [39]:
import numpy as np

In [40]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [41]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [42]:
print(type(b))

<class 'numpy.ndarray'>


In [43]:
print(type(a))

<class 'torch.Tensor'>


In [45]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [46]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Both a and b are changed because both point to the same memory location.

In [47]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [48]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [49]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [50]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
